POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Cathy McCartson",
    "number": "0005-5555-5555"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "number": "0005-5555-5555"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Maggie Sim",
    "number": ""
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Cu",
    "number": "1111"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Success 5",
    "number": "09-1234556"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Success 3",
    "number": "040-22334455"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Failure 1",
    "number": "1234556"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Failure 4",
    "number": "1-22334455"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Failure 5",
    "number": "10-22-334455"
}